### ISSUE TITLE
OpenStreetMap

### ISSUE THREAD

**Issue by davidar** [ipfs/archives#11]
http://www.openstreetmap.org/

- [x] mirror [latest planet.osm.pbf](https://archive.org/download/osm-pbf-20150824/planet-150824.osm.pbf) to ipfs ([here](http://gateway.ipfs.io/ipfs/QmVGatvrxQwfEA6sqUcUyvneHtJ5rqkz45joRCwqc7hWnx))
- [x] [convert to vector tiles](https://vimeo.com/106228141)
- [x] OSM [viewer](http://wiki.openstreetmap.org/wiki/Vector_tiles#Client.2Frenderer) on ipfs
- [x] install necessary tools on pollux
- [ ] write a proper configuration for tilemaker
- [ ] make vector tiles for entire planet
- [ ] clean up the viewer to look nice

Links:

- https://github.com/osm-for-schools/osm-bright.tm2source

License: [ODbL](http://opendatacommons.org/licenses/odbl/summary/)
CC: @zignig

**Comment by whyrusleeping** [comment]
:+1: this would be soo cool.

**Comment by zignig** [comment]
:+1:

**Comment by davidar** [comment]
Ok, I think we're basically looking for [hoverboard](https://github.com/devTristan/hoverboard) by @devTristan, but loading all of its resources from ipfs. @mapbox and @mapzen have also published a lot of useful tools and data.

Relevant links:

- http://blog.mathieu-leplatre.info/serve-your-map-layers-with-a-usual-web-hosting-service.html
- http://gis.stackexchange.com/questions/125037/self-hosting-mapbox-vector-tiles

**Comment by jbenet** [comment]
:+1: i would _looooove_ love love this. I think we can do this very easily now. once ipld json-ness lands, this will be a trivial import (yay JSON!)

**Comment by davidar** [comment]
The major obstacle is converting the raw data dump into a format that the js viewers can read. I haven't had much luck with this yet, is anyone more familiar with osm able to lend a hand? :)

**Comment by davidar** [comment]
And the winner is [tilemaker](https://github.com/systemed/tilemaker) by @systemed :)

Here's a [semi-functional OSM viewer on IPFS](https://gateway.ipfs.io/ipfs/QmcBfgYXfRwE3sJtqTyFh1fDna9RfbCCAY3CcwnndXwtJ1/)! It still loads some external js, but all the tiles are hosted on ipfs :)

**Comment by jbenet** [comment]
@davidar this is really great! i've been waiting so long for this. :+1:

**Comment by zignig** [comment]
interesting, have some go code for tile caches and osm stuff. will dig up.

**Comment by jbenet** [comment]
@davidar would be nice if the OSM viewer accepted a query params to specify things like the data root. (i've been using `<url>#<ipfs-path>` but `#` is a bad idea because it prevents regular anchor action. i now think  `?somekey=<ipfs-path>` is better

**Comment by zignig** [comment]
https://github.com/qedus/osmpbf is pretty good , i've used if before.

I think general GIS storage in IPFS will create some interesting options.

**Comment by davidar** [comment]
Hmm, from [here](http://gis.stackexchange.com/questions/151266/offline-vector-tile-map-for-android-and-ios-app) about generating vector tiles:

> We (in Nutiteq) spent many man-months to optimize it and to get it right for OSM data, and as far as I've heard from Skobbler and Mapbox guys they have done the same.

Since these companies offer tile servers as a paid service, I suspect they aren't going to be willing to share all their secrets :(

The most I've been able to find out about how mapbox generates their tiles is from a single slide in that video I linked earlier (@16min), transcript below:

```sh
# headless export

npm install mapnik mbtiles \
 tilelive tilelive-bridge

./node_modules/tilelive/bin/tilelive-copy \
  bridge:///Users/dane/data/world-borders.tm2source/data.xml \
  --bbox=-180,-85,180,85 \
  export.mbtiles

# data.xml is created by Mapbox Studio
```

The problem is that Mapbox Studio uses way to much memory for me to even consider trying to use it to generate worldwide tiles myself.

*However*, I also found @opensciencemap, who have a very cool [vector tile viewer](http://www.opensciencemap.org/map/). As a a non-profit research project, hopefully they might be more open to collaboration. I'll try floating the idea with them.

**Comment by whyrusleeping** [comment]
@davidar i have a few machines with a lot of memory, let me know if you want me to do anything for you

**Comment by tmcw** [comment]
@davidar happy to help out with understanding & creating vector tiles. The main design decision you need to make first on this task is whether you're creating vector tiles for people to use as basemaps, or as data. For instance, the Mapbox Streets tileset is for visualization, and the [OSM QA tiles](http://osmlab.github.io/osm-qa-tiles/) are for data and analysis. If you're creating tiles for visualization, they _can't_ practically contain all data, and will need to bake in assumptions about what is shown at each zoom level and what map designs are appropriate. These assumptions vary between different maps, hence why there isn't one universal way to 'convert' OSM data to visualization-ready vector tiles.

**Comment by davidar** [comment]
@tmcw that would be brilliant :). My immediate interest is in visualisation (but I suspect @zignig would be very interested in the data analysis side). It would be great to have enough data to do things like routing, but that's not an immediate priority. I don't have any specific requirements other than:

- something that looks better than the crappy demo I made (linked a couple of comments ago)
- reasonable file sizes (preferably the total size should be not significantly larger than the raw osm data)

I'd very much appreciate it if your we're able to offer guidance as to how to achieve this. Working with geo data isn't exactly my area (outside of geostats stuff like kriging, etc).

**Comment by almereyda** [comment]
@zignig We are investigating using IPFS as an archival option for geodata in @transformap. But this is not the OSM topic anymore and rather links to a world of distributed geodata. You are always invited to join our https://discourse.transformap.co

**Comment by jbenet** [comment]
@almereyda we'd love to help however we can. maybe open a different issue in this repo?

**Comment by davidar** [comment]
http://osm2vectortiles.org/

CC: @lukasmartinelli @manuelroth

**Comment by lukasmartinelli** [comment]
> Since these companies offer tile servers as a paid service, I suspect they aren't going to be willing to share all their secrets :(

Creating vector tiles for the entire world is a big undertaking. At https://github.com/osm2vectortiles/osm2vectortiles we have a completly open process how to generate vector tiles for the entire planet but we dump everthing into a PostGIS database first.

We also looked at tilemaker but ruled it out for scaling to the entire planet. To scale up you need a lot of infrastructure as well (like 6 x 50GB RAM, 16 core servers).

I don't know exactly what the goal of this IPFS project regarding OSM is but we love to collaborate.
If you want to preserve data then vector tiles is perhaps the wrong format - it is not a loss less format.

We love to collaborate. We can also sit together in a Skype call (lukas.martinelli) to discuss questions regarding the entire vector tiles from OSM topic.

**Comment by davidar** [comment]
@lukasmartinelli Glad to hear you're interested in collaborating :)

The goal of this particular issue is to get an OSM viewer running on IPFS. Lossiness isn't much of a concern as we can already just mirror the raw OSM dumps.

The major constraint is that all the tiles need to be stored in a static filesystem structure, without any reliance on server-side processing (ie. `tileserver-php` isn't an option). Is this likely to be problematic?

**Comment by lukasmartinelli** [comment]
> The major constraint is that all the tiles need to be stored in a static filesystem structure, without any reliance on server-side processing (ie. tileserver-php isn't an option). Is this likely to be problematic?

If you serve vector tiles only **you can extract and serve them on a static fileserver**. There are examples that do vector tiles serving from S3 (but beware uploading 360 million files to S3 takes forever). You cannot do some features like supporting a filter zoom level or supporting other schemes like TMS but it works.

> The goal of this particular issue is to get an OSM viewer running on IPFS. Lossiness isn't much of a concern as we can already just mirror the raw OSM dumps.

Generating vector tiles from the OSM dump just to get a mirror is quite a task. Probably better to not pregenerate all the vector tiles like we do it but serve them dynamically from the specific OSM dump.
Would be cool if tilemaker can handle a request for a tile and then create vector tiles from OSM just for that tile and then run this as a server.

**Comment by davidar** [comment]
> If you serve vector tiles only you can extract and serve them on a static fileserver. There are examples that do vector tiles serving from S3 (but beware uploading 360 million files to S3 takes forever).

Awesome.

@whyrusleeping Will ingesting that number of files be an issue for us?

> Generating vector tiles from the OSM dump just to get a mirror is quite a task. Probably better to not pregenerate all the vector tiles like we do it but serve them dynamically from the specific OSM dump.

For the purposes of this issue, IPFS would be functioning as a *distributed CDN*. The benefit over traditional CDNs is that it is peer-to-peer, so continues to function even in disconnected/offline networks. [This article](https://ipfs.io/ipfs/QmNhFJjGcMPqpuYfxL62VVB9528NXqDNMFXiqN5bgFYiZ1/its-time-for-the-permanent-web.html) is a good summary of IPFS if you're interested in more details.

Serving tiles dynamically isn't an option as there is no server. All the processing has to be done either in advance or client-side.

**Comment by davidar** [comment]
Perhaps we should move this issue to ipfs/apps#25 as it isn't specifically archival-related.
