### ISSUE TITLE
Provide Instructions for setting up data.gov Collaborators' Testbed Network

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/archives#116]
- [x] provide instructions on how to set up the peer ipfs nodes @whyrusleeping, @flyingzumwalt
- [x] create any necessary config files, setup/install scripts, etc @whyrusleeping 
- [x] do preliminary load testing #126 (@whyrusleeping)

**Comment by flyingzumwalt** [comment]
Discussion on sprint planning: can we do this without merging "private networks"? They could modify the iptables, but writing a scipt to help with that might be harder than landing private networks.

**Comment by flyingzumwalt** [comment]
@lgierth suggests we might be able to just use ip address filters.

**Comment by flyingzumwalt** [comment]
This will use the new "private networks" code that @Kubuxu has just finished. It's not "ready for release" due to incomplete UX, but the plumbing will work for these tests. See https://github.com/ipfs/archives/issues/123

**Comment by flyingzumwalt** [comment]
@Kubuxu suggests that for such a small network, which will not use DHT, we will need to deploy some seed nodes.  To handle lack of dht we might be able to have nodes connect directly with each other.

**Comment by flyingzumwalt** [comment]
What's involved in create any necessary config files, setup/install scripts, etc:

* turn off DHT
* push change to bitswap so that it doesn't provide things when it fetches
* manual routing: probably client mode
* add with local
* start daemon with nosync
* no re-providing

**Comment by whyrusleeping** [comment]
So, on the side of the people adding the data, you'll use ipfs-pack:
```
cd /dataset/directory
ipfs-pack make
ipfs-pack serve
```

For the people doing mirroring, I will prepare a script that does roughly the following:
```
ipfs init
ipfs config --json Datastore.NoSync true
ipfs config Reprovider.Interval "0"


# then for starting the daemon:
ipfs daemon --routing=none
```

The caveat with starting the daemon this way is you will have to manually connect peers to start the transfers.

**Comment by flyingzumwalt** [comment]
Questions that this leaves unanswered:
- How will mirrors install ipfs? Which version? Downloaded from where?
- How will they "manually connect peers"?

Think of it this way: If they were to do this while you were on vacation on mars, meaning they can't reach you for assistance, what instructions do they need?

**Comment by whyrusleeping** [comment]
> How will mirrors install ipfs? Which version? Downloaded from where?

They should download it from dist.ipfs.io

> How will they "manually connect peers"?

When running `ipfs-pack serve` that nodes peer ID and some addresses its listening on should be printed out. The mirrors should then run `ipfs swarm connect ADDRESS/ipfs/PEERID` where address is a public address printed out by the ipfs-pack serve, and PEERID is the peer ID of the serving node. This part might need to be made a little easier. We could instead make sure that the `ipfs-pack` node has a public IP, and then have the mirrors set to bootstrap to it automatically.

**Comment by whyrusleeping** [comment]
If the `ipfs-pack` node has a public IP address, we get its multiaddr and have the mirrors set up bootstrapping to it during the init step:

```
ipfs bootstrap rm --all
ipfs bootstrap add /ip4/1.2.3.4/tcp/9999/ipfs/QmIpfsPackPEerId
```

Then their nodes would auto connect. This is probably the best way to make this work.

**Comment by flyingzumwalt** [comment]
@whyrusleeping should the people posting the data through ipfs-pack do anything to suppress routing, DHT, etc? You've only given instructions for the mirrors to do that. Was that intentional?

**Comment by flyingzumwalt** [comment]
@whyrusleeping please review the instructions I've posted here: https://github.com/ipfs/archives/pull/135
Are they accurate?

**Comment by flyingzumwalt** [comment]
The collaborators can now set up their ipfs nodes by following the [Instructions for Replicating Large Amounts of Data with Minimal Overhead](https://github.com/ipfs/archives/tree/master/tutorials/replicating-large-datasets). Note: we're recommending an approach that requires the source/provider (@mejackreed) to run their node on a machine with a public IP address. The other nodes do not need public IP addresses.
