### ISSUE TITLE
Add the first 5 TB to IPFS and Publish the content to the DHT

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/archives#117]
Jack adds the first 5 TB to IPFS. The hashes get published to the testbed network's DHT

blocked by #95 and #98. Need ipfs-pack and filestore working before Jack starts loading data into IPFS. In the meantime, we will be load-testing IPFS on a separate cluster. (see #126)

**Comment by flyingzumwalt** [comment]
Don't do this until ipfs-pack and filestore are ready to go.

**Comment by lgierth** [comment]
This is done now -- the cdn.media.ccc.de mirror has grown to 5.4T: #52 

Hash is on archives.ipfs.io.
