### ISSUE TITLE
Figure out how to set up the Testbed Network

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/archives#123]
Figure out how to do #116.

Discussion on sprint planning: can we do this without merging "private networks"? They could modify the iptables, but writing a scipt to help with that might be harder than landing private networks.

@lgierth suggests we might be able to just use ip address filters.

**Comment by Kubuxu** [comment]
I have Private Networks working, it isn't in "Release Ready" state but for tests and test deployment should be ok.
