### ISSUE TITLE
Self-updating IPFS webapps

### ISSUE THREAD

**Issue by cakenggt** [ipfs/archives#140]
I recently created a file tracking service called [Akasha](http://localhost:8080/ipfs/QmUeeLb9WSYas4kMLGNfZDMgV2pREx79UUr7wjRwN7X6Ah/) and I wanted to keep updating it without having to give everyone a new link every time. Normally people are pointed to IPNS when they have this problem, and I used this for about 5 days before I ran into a problem: IPNS de-resolves after 12-48 hours. So my site went "offline" over the weekend because I didn't bother turning on my computer. I didn't want to have to commit to keeping the IPNS record current for forever, especially since IPFS is supposed to be all about permanent files, so I came up with another solution.

The long and short of it is that when the IPFS file linked above is loaded up, it attempts to make a `HEAD` request of the IPNS record that would ideally point to my most recent build. The IPFS file itself has all the basic functionality needed to use the service, but better functionality and looks can be found with the most current file. Additionally, a `HEAD` request won't return any data, just whether or not the address is able to be resolved (more or less), so it is enough to check if the IPNS record is still resolving. If the request is successful, the user is prompted to decide if they want to switch to the new version, and that's how I solved that problem.

The reason the old file and new file are able to provide the same functionality is that I have them connecting to an API service on the normal internet for information, so they would be able to show the same info either way. However, if that should ever go down, the newest version of the site always has a backup of the db in the IPFS directory, which it then reads from instead, so that the site will always be able to be up in some incarnation.

**Comment by hsanjuan** [comment]
Thanks, sounds like a nice way of getting around some IPNS problems.

Since I'm cleaning up old issues, I will close this one as it is not actionable and we use DNS normally. If interested, you are welcome to post at https://discuss.ipfs.io.
