### ISSUE TITLE
textfiles.com

### ISSUE THREAD

**Issue by brannondorsey** [ipfs/archives#155]
I'm interested in adding [textfiles.com](http://textfiles.com/) to the archive. Jason Scott is an incredible archivist, and textfiles.com is arguably one of his seminal "saves". There is so much early internet/BBS lore in those files. I've created a mirror of the site, and will submit a PR shortly.

**Comment by spiko** [comment]
It would be weird if there were no viruses in here :) 
Anyway, not sure how this auto cleaning will impact the sharing process.

![image](https://user-images.githubusercontent.com/839824/51797631-518fba00-2207-11e9-86b7-b4508cb3ad84.png)
