### ISSUE TITLE
Deprecate archives.ipfs.io?

### ISSUE THREAD

**Issue by victorb** [ipfs/archives#179]
Since we now lists datasets on awesome.ipfs.io, maybe we should just deprecate the archives.ipfs.io website and add a link to the category on awesome.ipfs.io instead? We should still have isolated discussions here but the results published on awesome.ipfs.io.

**Comment by davidak** [comment]
Sounds like a good idea.

Right now there are only 8 datasets on https://awesome.ipfs.io/categories/datasets/ but 15 on https://archives.ipfs.io/. They should get migrated first.

Then a 301 redirect from https://archives.ipfs.io/ to https://awesome.ipfs.io/categories/datasets/ would be good.

Should there be any hint to the archiving efforts in this repo?

**Comment by hacdias** [comment]
@Stebalien what about this?

**Comment by Stebalien** [comment]
Sounds like a great idea, are you volunteering?

**Comment by hacdias** [comment]
If it's something to do, I can move the missing datasets to `awesome.ipfs.io`, yes.

**Comment by Stebalien** [comment]
1. Move the missing datasets.
2. Setup the redirect (or make sure infra does it).
3. Update the README on this repo with instructions on how to get datasets added (PR the awesome IPFS repo?).

**Comment by hacdias** [comment]
@Stebalien can you handle the redirect or should we ping someone from Infra?

**Comment by Stebalien** [comment]
I can't. @ipfs/wg-infrastructure?

**Comment by hsanjuan** [comment]
I have redirected the domain

**Comment by hsanjuan** [comment]
My browsers try to open archives.ipfs.io on HTTPs which breaks the redirection though, I´m not sure why.

**Comment by hacdias** [comment]
JUst tested and the same is happening here

**Comment by hsanjuan** [comment]
might have to do with:

`< strict-transport-security: max-age=31536000; includeSubDomains; preload`

in `ipfs.io` and `gateway.ipfs.io`... which means we'll need to setup a special redirect rule on nginx

**Comment by hacdias** [comment]
@Stebalien since the redirect isn't working as expected, could you change the URL of the repository description to awesome.ipfs.io/datasets?

**Comment by Stebalien** [comment]
Sure. But we also need to fix the redirect.
