### ISSUE TITLE
IRC logs

### ISSUE THREAD

**Issue by fazo96** [ipfs/archives#24]
I don't know if there's a chan log already, but a bot creating it and storing it in ipfs looks like a great idea to me. The only issue is how to split messages into files:

Do we use a file for every day containing all the messages of the day? Or we divide them by the hour? Or some other way? By the day sounds the best for me.

**Comment by jbenet** [comment]
Let's generalize this to hosting all botbot.me logs



—

**Comment by davidar** [comment]
@BotBotMe @bartTC @ipmb @yml Would mirroring botbot.me logs on IPFS be possible?

**Comment by ipmb** [comment]
I don't know much about IPFS. I'd need more information on what's involved to give you an answer.

**Comment by jbenet** [comment]
@ipmb it's a "distributed web" filesystem. all content (websites, data, arbitrary files) gets permanent content addresses. for example, our website: https://ipfs.io -- can be accessed by any ipfs gateway:

- https://ipfs.io/ipns/ipfs.io
- http://erebor.benet.ai:8080/ipns/ipfs.io
- http://celebdil.benet.ai:8080/ipns/ipfs.io
- http://localhost:8080/ipns/ipfs.io <-- if you're running it locally
- fs://ipns/ipfs.io <-- if you had the right handler installed
- `/ipns/ipfs.io` <-- if you had ipfs mounted locally

And the content served is also accessible at content-addressed URIs:

- https://ipfs.io/ipfs/QmeQT76CZLBhSxsLfSMyQjKn74UZski4iQSq9bW7YZy6x8
- http://erebor.benet.ai:8080/ipfs/QmeQT76CZLBhSxsLfSMyQjKn74UZski4iQSq9bW7YZy6x8
- http://celebdil.benet.ai:8080/ipfs/QmeQT76CZLBhSxsLfSMyQjKn74UZski4iQSq9bW7YZy6x8
- http://localhost:8080/ipfs/QmeQT76CZLBhSxsLfSMyQjKn74UZski4iQSq9bW7YZy6x8 <-- if you're running it locally
- fs://ipfs/QmeQT76CZLBhSxsLfSMyQjKn74UZski4iQSq9bW7YZy6x8 <-- if you had the right handler installed
- `/ipfs/QmeQT76CZLBhSxsLfSMyQjKn74UZski4iQSq9bW7YZy6x8` <-- if you had ipfs mounted locally

What this boils down to is that -- with botbot.me -- we could:
- [ ] provide a content-addressed mirror / archive
- [ ] make the log viewer website distributed (like our ipfs.io site)

And have URIs like:
- https://ipfs.io/ipns/botbot.me/ipfs <-- the `#ipfs` channel archives mutable addr
- https://ipfs.io/ipns/botbot.me/ipfs/raw <-- the `#ipfs` channel archives raw data
- https://ipfs.io/ipfs/QmdmxWiLubwjDCk8UGXvihtpmWcopx4a6f8n7YYBnreGE6 <-- say, one snapshot.

**Comment by ipmb** [comment]
I won't have time to take this on, but the project is open source. If you'd like to see this functionality, fell free to contribute. I recommend starting by opening an issue at https://github.com/botbotme/botbot-web and discussing the general approach you would take before writing any code. We would want to know that it wouldn't cause any maintenance burden prior to accepting a pull request.

**Comment by Mikaela** [comment]
Will this issue be closed as there hasn't been activity in three years, GDPR is here and [BotBotMe](https://lincolnloop.com/blog/saying-goodbye-botbotme/) is closing in ten days?

**Comment by fazo96** [comment]
Yeah. We can reopen is there is any interest
