### ISSUE TITLE
http://gen.lib.rus.ec/

### ISSUE THREAD

**Issue by rht** [ipfs/archives#30]

**Comment by rajputsandip** [comment]
Emulsion Polymerization and Emulsion Polymers

**Comment by duttaditya18** [comment]
@rajputsandip If you were looking for the book : "Emulsion Polymerization and Emulsion Polymers", see [this link](http://gen.lib.rus.ec/book/index.php?md5=AFE5CF19ED5F5CF25433FFF7923509E3).
