### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by davidar** [ipfs/archives#44]
@jbenet What do you think of this one?

![ipfs-archives](https://cloud.githubusercontent.com/assets/24291/11561277/0989c190-9a12-11e5-91ff-6d00858ec07c.png)

Books derived from the [Noun Project](https://thenounproject.com/term/book/)

**Comment by eminence** [comment]
This is a public domain icon? or Creative-Commons license? or one of the paid-unlimited-use icons?

**Comment by jbenet** [comment]
i like the idea! 

this iteration seems very busy, mostly from the ipfs logo clashing with all the other lines.

**Comment by davidar** [comment]
@eminence the latter two (dual license)

@jbenet yeah, I wasn't particularly happy about that either. Any suggestions?

**Comment by davidar** [comment]
This is what it looks like without the ipfs logo superimposed, fwiw:

![ipfs-archives](https://cloud.githubusercontent.com/assets/24291/11582734/d3b89bc2-9a9d-11e5-935f-b12662396e20.png)

**Comment by pokeball99** [comment]
what about making a logo based on these "specs"?: https://github.com/bibanon/bibanon/wiki/Bibliotheca-Anonoma-Logo

**Comment by davidar** [comment]
@pokeball99 sorry, I can't say I find those logos all that aesthetically pleasing 

@jbenet thoughts on the latest iteration?

**Comment by jbenet** [comment]
@davidar it doesnt make it clear these are ipfs archives. the hex/cube is too subtle. but yeah, it's nice and simple. idk, maybe go ahead and use it and we can upgrade it later
