### ISSUE TITLE
hosted JS libraries

### ISSUE THREAD

**Issue by eminence** [ipfs/archives#47]
Basically a mirror of https://developers.google.com/speed/libraries/

The following libraries are included, each with an update script and a `datapackage.json` file

* angular_js
* angular_material
* dojo
* ext_core
* jquery
* jquery_mobile
* jquery_ui
* mootools
* prototype
* scriptaculous
* spf
* swfobject
* three.js
* webfontloader

https://ipfs.io/ipns/em32.net/archives/hosted_js

(At the time of this writing, the latest version is `/ipfs/QmYjAUMQDCPYiE9A1wjczXHvAMhYiBwhSu3SUxNoadqJCT`)

CC #35

**Comment by davidar** [comment]
@eminence cool

I might fold this issue into #35 since it's a subset of that mirror
