### ISSUE TITLE
33c3 Fahrplan / schedule

### ISSUE THREAD

**Issue by lgierth** [ipfs/archives#78]
Version "NOT A BUG": https://ipfs.io/ipfs/QmNQ1TQzC3D4MMJFN5LVCKPBryRg968QTCvQ29miamxQq8

I'll try to keep this updated

**Comment by lgierth** [comment]
Command used: `screen bash -c "wget --mirror --convert-links --no-parent -nv https://fahrplan.events.ccc.de/ 2>&1 | tee fahrplan.log"`

**Comment by lgierth** [comment]
Latest version "DUPLICATE": https://ipfs.io/ipfs/QmUtWbi3Dj9ragCQ52KWjy4gg1XcPTFqb8ETa3PvBQJveQ

**Comment by lgierth** [comment]
Latest version "COSMIC RADIATION": https://ipfs.io/ipfs/QmZNrcdGbdHmFY5UypnSAnbXvoV4mM4vSTv2EcWhWjbA31/

**Comment by lgierth** [comment]
Latest version "PEBCAK": ipfs.io/ipfs/QmYdtqfAe3yPD9vSukGMENmTj8zQ6fmuKp3hQDLyt74Roy

**Comment by VictorBjelkholm** [comment]
Event is over, gonna close this.
