### ISSUE TITLE
Story: [ipfs-pack] Create or Update a pack manifest file

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/archives#96]
Use [`pack make`](https://github.com/ipfs/ipfs-pack/blob/master/spec.md#ipfs-pack-make-create-or-update-a-pack-manifest) to create or update a PackManifest file. See [disussion about format for PackManifest files](https://github.com/ipfs/ipfs-pack/issues/2)

**Comment by rht** [comment]
Would the `resources` field in https://github.com/ipfs/archives/pull/101/files#diff-c2efd16ce17aedc8d326b8740770ec13 count as a manifest file?

**Comment by flyingzumwalt** [comment]
Please refer to the [draft proposal for ipfs-pack](https://github.com/ipfs/notes/issues/205) for technical details about ipfs-pack and its manifest files.

**Comment by rht** [comment]
If I read the proposal correctly:
- a manifest file is a flat hash table of the filenames, almost like the output of `ipfs add`
- No further metadata are specified, such as byte boundaries like in a `.torrent` file, permission string, no size, mime type

**Comment by flyingzumwalt** [comment]
@rht if you have comments/questions about the draft proposal, please post them on that issue. Otherwise they will be lost from the thread of conversation.
