### ISSUE TITLE
Review ipfs-pack draft proposal

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/archives#99]
Review [Issue: Proposing some tooling for datasets (ipfs-pack and stuff)](https://github.com/ipfs/notes/issues/205)

Implementing a basic version of pack should be relatively simple and would be quite useful because it allows a dataset to be a freestanding content-addressed thing regardless of how you're storing it. Among other things, this allows us to simplify the filestore requirements.

Related Stories: #98

**Comment by kevina** [comment]
What exactly are the "filestore requirements."  that seams very odd that _now_ we are working on this, considering I already have a very functional implementation?

**Comment by flyingzumwalt** [comment]
@kevina I recommend posing this question on Issue #85 . My understanding is that @whyrusleeping and @jbenet think the existing implementation is too complicated.  They plan to review the filestore implementation and are considering the "Concise Filestore spec" linked to from that issue.

**Comment by kevina** [comment]
@flyingzumwalt okay.  the question wasn't really directed at you.

**Comment by jbenet** [comment]
@kevina context: https://github.com/ipfs/pm/issues/309#issuecomment-273626297

**Comment by jbenet** [comment]
I need to update the ipfs-pack spec for the work we're doing this sprint.

**Comment by kevina** [comment]
There is a good chance I can help with ipfs-pack but I want to first work on any filestore specific issues so I am waiting for @jbenet notes on my code and/or meeting before I commit any time to this sprint.

**Comment by flyingzumwalt** [comment]
Results of this review: [ipfs/ipfs-pack repo](https://github.com/ipfs/ipfs-pack) with [new ipfs-pack spec](https://github.com/ipfs/ipfs-pack/blob/master/spec.md)
